"""30 случайных вспышек судьбы (короткие ивенты 2–3ч)."""

from __future__ import annotations

# Схема: title, desc, buffs, debuffs + числовые модификаторы как у WORLD_EVENTS
# work_mult, raid_mult, tax_add, raid_cd_mult, loot_mult, smuggle_mult, raid_block, raid_night

FLASH_EVENTS: dict[str, dict] = {
    "comet": {
        "title": "☄ Падение кометы",
        "desc": "Небо вспыхнуло — удача сыплется на старателей.",
        "buffs": "Работы +40% · шанс лута +50%",
        "debuffs": "—",
        "work_mult": 1.4,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 1.5,
    },
    "drought": {
        "title": "🏜 Засуха",
        "desc": "Земля трескается, колодцы мелеют.",
        "buffs": "—",
        "debuffs": "Работы −30%",
        "work_mult": 0.7,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
    },
    "market_boom": {
        "title": "📈 Биржа в огне",
        "desc": "Купцы орут цены громче барабанов.",
        "buffs": "Работы +30%",
        "debuffs": "Рейды −15% добычи",
        "work_mult": 1.3,
        "raid_mult": 0.85,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
    },
    "bandits": {
        "title": "🗡 Налёт разбойников",
        "desc": "Дороги кишат шайками — кто смел, тот сыт.",
        "buffs": "Рейды +30% добычи",
        "debuffs": "Работы −10%",
        "work_mult": 0.9,
        "raid_mult": 1.3,
        "tax_add": 0.0,
        "raid_cd_mult": 0.9,
    },
    "fog": {
        "title": "🌫 Густой туман",
        "desc": "Ни зги не видно — идеально для теней.",
        "buffs": "Контрабанда ×1.4 · КД рейда чуть дольше",
        "debuffs": "Рейды −10% добычи",
        "work_mult": 1.0,
        "raid_mult": 0.9,
        "tax_add": 0.0,
        "raid_cd_mult": 1.15,
        "smuggle_mult": 1.4,
    },
    "street_fair": {
        "title": "🎪 Уличная ярмарка",
        "desc": "Смех, пряники и лёгкие налоги.",
        "buffs": "Работы +25% · налог −3 п.п.",
        "debuffs": "—",
        "work_mult": 1.25,
        "raid_mult": 1.0,
        "tax_add": -0.03,
        "raid_cd_mult": 1.0,
    },
    "eclipse": {
        "title": "🌑 Затмение",
        "desc": "Солнце скрылось — звери и армии проснулись.",
        "buffs": "Рейды +40%",
        "debuffs": "Работы −25%",
        "work_mult": 0.75,
        "raid_mult": 1.4,
        "tax_add": 0.0,
        "raid_cd_mult": 0.85,
    },
    "spring_rain": {
        "title": "🌧 Весенний ливень",
        "desc": "Поля пьют воду, казны пьют налоги… поменьше.",
        "buffs": "Работы +20% · налог −2 п.п.",
        "debuffs": "—",
        "work_mult": 1.2,
        "raid_mult": 1.0,
        "tax_add": -0.02,
        "raid_cd_mult": 1.0,
    },
    "blizzard": {
        "title": "❄ Метель",
        "desc": "Снег по пояс — и работать, и воевать тяжело.",
        "buffs": "—",
        "debuffs": "Работы −20% · рейды −15%",
        "work_mult": 0.8,
        "raid_mult": 0.85,
        "tax_add": 0.0,
        "raid_cd_mult": 1.2,
    },
    "pirate_tide": {
        "title": "🏴‍☠️ Прилив пиратов",
        "desc": "Порт гудит: чёрные паруса и чёрный рынок.",
        "buffs": "Контрабанда ×1.5 · рейды +10%",
        "debuffs": "Налог +3 п.п.",
        "work_mult": 1.0,
        "raid_mult": 1.1,
        "tax_add": 0.03,
        "raid_cd_mult": 1.0,
        "smuggle_mult": 1.5,
    },
    "empire_tax": {
        "title": "📜 Имперский сбор",
        "desc": "Курьеры разносят указы о «временном» налоге.",
        "buffs": "—",
        "debuffs": "Налог стран +8 п.п.",
        "work_mult": 1.0,
        "raid_mult": 1.0,
        "tax_add": 0.08,
        "raid_cd_mult": 1.0,
    },
    "tax_amnesty": {
        "title": "🕊 Налоговая амнистия",
        "desc": "На сегодня казна закрывает глаза.",
        "buffs": "Налог ≈ 0",
        "debuffs": "—",
        "work_mult": 1.05,
        "raid_mult": 1.0,
        "tax_add": -1.0,
        "raid_cd_mult": 1.0,
    },
    "forge_fever": {
        "title": "🔥 Лихорадка кузниц",
        "desc": "Молоты не замолкают до рассвета.",
        "buffs": "Работы +35%",
        "debuffs": "—",
        "work_mult": 1.35,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
    },
    "truce_bells": {
        "title": "🔔 Колокола перемирия",
        "desc": "Ни один меч не должен звенить.",
        "buffs": "Работы +10%",
        "debuffs": "Рейды запрещены",
        "work_mult": 1.1,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "raid_block": True,
    },
    "blood_tide": {
        "title": "🩸 Кровавый прилив",
        "desc": "Море краснеет — армии идут напролом.",
        "buffs": "Рейды +55%",
        "debuffs": "Работы −30%",
        "work_mult": 0.7,
        "raid_mult": 1.55,
        "tax_add": 0.0,
        "raid_cd_mult": 0.75,
    },
    "lucky_stars": {
        "title": "✨ Звёзды удачи",
        "desc": "Судьба подмигивает каждому старателю.",
        "buffs": "Шанс лута ×2.5 · работы +10%",
        "debuffs": "—",
        "work_mult": 1.1,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 2.5,
    },
    "empty_pockets": {
        "title": "🪙 Пустые карманы",
        "desc": "Даже крысы обходят кошельки стороной.",
        "buffs": "—",
        "debuffs": "Работы −40% · лут ×0.5",
        "work_mult": 0.6,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 0.5,
    },
    "caravan": {
        "title": "🐪 Богатый караван",
        "desc": "Шёлк, специи и слухи о лёгкой добыче.",
        "buffs": "Работы +20% · лут ×1.4",
        "debuffs": "—",
        "work_mult": 1.2,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 1.4,
    },
    "plague_rats": {
        "title": "🐀 Чумные крысы",
        "desc": "Скрежет в амбарах и кашель на улицах.",
        "buffs": "—",
        "debuffs": "Работы −35% · налог +4 п.п.",
        "work_mult": 0.65,
        "raid_mult": 1.0,
        "tax_add": 0.04,
        "raid_cd_mult": 1.0,
        "loot_mult": 0.85,
    },
    "golden_hour": {
        "title": "🌅 Золотой час",
        "desc": "Солнце целует монеты — всё даётся легче.",
        "buffs": "Работы ×1.7 · лут ×1.3",
        "debuffs": "—",
        "work_mult": 1.7,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 1.3,
    },
    "siege_drums": {
        "title": "🥁 Барабаны осады",
        "desc": "Ритм войны ускоряет ноги воинов.",
        "buffs": "Рейды +25% · КД рейда быстрее",
        "debuffs": "Работы −5%",
        "work_mult": 0.95,
        "raid_mult": 1.25,
        "tax_add": 0.0,
        "raid_cd_mult": 0.7,
    },
    "envoy": {
        "title": "🕊 Посольство мира",
        "desc": "Белые флаги на всех башнях.",
        "buffs": "Работы +15% · налог −2 п.п.",
        "debuffs": "Рейды запрещены",
        "work_mult": 1.15,
        "raid_mult": 1.0,
        "tax_add": -0.02,
        "raid_cd_mult": 1.0,
        "raid_block": True,
    },
    "black_market": {
        "title": "🕶 Чёрный рынок",
        "desc": "В переулках шепчут цены без жалости.",
        "buffs": "Контрабанда ×1.6",
        "debuffs": "Налог +5 п.п. · рейды −10%",
        "work_mult": 1.0,
        "raid_mult": 0.9,
        "tax_add": 0.05,
        "raid_cd_mult": 1.0,
        "smuggle_mult": 1.6,
    },
    "harvest_moon": {
        "title": "🌕 Урожайная луна",
        "desc": "Серпы блестят, амбары не закрываются.",
        "buffs": "Работы +50%",
        "debuffs": "—",
        "work_mult": 1.5,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
    },
    "ash_fall": {
        "title": "🌋 Пепел с неба",
        "desc": "Вулкан далеко, но пепел здесь.",
        "buffs": "—",
        "debuffs": "Работы −25% · лут ×0.8",
        "work_mult": 0.75,
        "raid_mult": 1.05,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 0.8,
    },
    "royal_pardon": {
        "title": "👑 Королевское прощение",
        "desc": "Император улыбнулся — казна молчит.",
        "buffs": "Налог ≈ 0 · работы +10%",
        "debuffs": "Рейды −10%",
        "work_mult": 1.1,
        "raid_mult": 0.9,
        "tax_add": -1.0,
        "raid_cd_mult": 1.0,
    },
    "storm_surge": {
        "title": "🌊 Штормовой вал",
        "desc": "Порты закрыты, контрабанда тонет.",
        "buffs": "—",
        "debuffs": "Работы −15% · контрабанда ×0.65",
        "work_mult": 0.85,
        "raid_mult": 1.0,
        "tax_add": 0.0,
        "raid_cd_mult": 1.1,
        "smuggle_mult": 0.65,
    },
    "relic_pulse": {
        "title": "💎 Пульс реликвий",
        "desc": "Древние вещи зовут искателей.",
        "buffs": "Лут ×2 · рейды +10%",
        "debuffs": "—",
        "work_mult": 1.0,
        "raid_mult": 1.1,
        "tax_add": 0.0,
        "raid_cd_mult": 1.0,
        "loot_mult": 2.0,
    },
    "mercenary_call": {
        "title": "⚔ Клич наёмников",
        "desc": "Мечи в аренду — дёшево и сердито.",
        "buffs": "Рейды +35%",
        "debuffs": "Работы −10%",
        "work_mult": 0.9,
        "raid_mult": 1.35,
        "tax_add": 0.0,
        "raid_cd_mult": 0.85,
    },
    "calm_seas": {
        "title": "⛵ Тихие моря",
        "desc": "Волны ласковы к купцам и контрабандистам.",
        "buffs": "Работы +15% · контрабанда ×1.25",
        "debuffs": "Рейды −10%",
        "work_mult": 1.15,
        "raid_mult": 0.9,
        "tax_add": 0.0,
        "raid_cd_mult": 1.05,
        "smuggle_mult": 1.25,
    },
}


def get_flash_def(key: str) -> dict | None:
    return FLASH_EVENTS.get(key)


def list_flash_keys() -> list[str]:
    return list(FLASH_EVENTS.keys())
